version: 2.1

orbs:
  win: circleci/windows@2.2.0

# Default actions to perform on each Emacs version
commands:
  setup:
    steps:
      - checkout
      - run:
          name: Install unzip
          command: apt-get update && apt-get install unzip
      - run:
          name: Install Eask
          command: curl -fsSL https://raw.githubusercontent.com/emacs-eask/cli/master/webinstall/install.sh | sh

  macos-setup:
    steps:
      - checkout
      - run:
          name: Install Emacs latest
          command: |
            echo "HOMEBREW_NO_AUTO_UPDATE=1" >> $BASH_ENV
            brew install homebrew/cask/emacs
      - run:
          name: Install unzip
          command: apt-get update && apt-get install unzip
      - run:
          name: Install Eask
          command: curl -fsSL https://raw.githubusercontent.com/emacs-eask/cli/master/webinstall/install.sh | sh

  setup-windows:
    steps:
      - checkout
      - run:
          name: Install Eask
          command: url.exe -fsSL https://raw.githubusercontent.com/emacs-eask/cli/master/webinstall/install.bat | cmd /Q

  test:
    steps:
      - run:
          name: Run tests
          command: |
            eask clean all
            eask package
            eask install
            eask compile

jobs:
{ EMACS_VERSION }
  test-macos-emacs-latest:
    macos:
      xcode: "14.0.0"
    steps:
      - macos-setup
      - test

  test-windows-emacs-latest:
    executor: win/default
    steps:
      - run:
          name: Install Emacs latest
          command: |
            choco install emacs
      - setup-windows
      - test

workflows:
  version: 2
  ci-test-matrix:
    jobs:
      { MATRIX_JOBS }
      - test-macos-emacs-latest
      - test-windows-emacs-latest
